a. List the areas you would look into when it comes to data preparation
b. Highlight any data idiosyncrasies that you might have observed
c. Put together a short presentation/document to tell a story about the key insights and
observations, taking into consideration dataset limitations.

List the areas you would look into when it comes to data preparation
Ans:
For data preparation I would like into consider variables purpose, occupation, shopping, accomdation,traveling mode.

b. Highlight any data idiosyncrasies that you might have observed.
Ans:
From this data it shows the tendency of the visitors from a country Indonesia.

In [ ]:
c. Put together a short presentation/document to tell a story about the key insights and
observations, taking into consideration dataset limitations.
Ans:
link: https://public.tableau.com/views/Internshipwork2/Story1?:language=en&:display_count=y&publish=yes&:origin=viz_share_link

In [1]:
import numpy as np
import pandas as pd

In [4]:
data=pd.read_excel('C:/Internship2/MockSurveyData.xlsx')

In [13]:
data.head(20)

case  Year    R.mth       date      intv_nam Country_residence  \
0     18  2015  January 2015-01-01     Cindy Liu         Indonesia   
1     41  2015  January 2015-01-01   Philip Chew         Indonesia   
2     43  2015  January 2015-01-01   Philip Chew         Indonesia   
3     44  2015  January 2015-01-01   Philip Chew         Indonesia   
4     45  2015  January 2015-01-01   Philip Chew         Indonesia   
5     46  2015  January 2015-01-01   Philip Chew         Indonesia   
6     47  2015  January 2015-01-01   Philip Chew         Indonesia   
7     49  2015  January 2015-01-01   Philip Chew         Indonesia   
8     50  2015  January 2015-01-01   Philip Chew         Indonesia   
9     51  2015  January 2015-01-01   Philip Chew         Indonesia   
10    52  2015  January 2015-01-01   Philip Chew         Indonesia   
11    53  2015  January 2015-01-01   Philip Chew         Indonesia   
12    54  2015  January 2015-01-01   Philip Chew         Indonesia   
13    55  2015  January 2015-01-01   Philip Chew         Indonesia   
14    56  2015  January 2015-01-01   Philip Chew         Indonesia   
15    57  2015  January 2015-01-01   Philip Chew         Indonesia   
16    58  2015  January 2015-01-01   Philip Chew         Indonesia   
17    59  2015  January 2015-01-01   Philip Chew         Indonesia   
18    60  2015  January 2015-01-01   Philip Chew         Indonesia   
19    61  2015  January 2015-01-01  Bay Poh Choo         Indonesia   

    City_residence      Purpose_grp  \
0       Yogyakarta          Leisure   
1            Batam          Leisure   
2            Batam          Leisure   
3            Batam          Leisure   
4            Batam  Others/ Refused   
5         Bengkulu          Leisure   
6            Batam          Leisure   
7            Batam          Leisure   
8            Batam          Leisure   
9   Tanjung Pinang          Leisure   
10  Tanjung Pinang          Leisure   
11         Jakarta          Leisure   
12           Batam          Leisure   
13       East Java          Leisure   
14         Lampung          Leisure   
15           Batam  Others/ Refused   
16           Batam          Leisure   
17           Batam          Leisure   
18       Palembang  Others/ Refused   
19        Surabaya          Leisure   

                                             Purpose  Weights_QTR  ...  \
0                              Holiday/ Rest & Relax   632.145161  ...   
1                              Holiday/ Rest & Relax   341.937500  ...   
2                              Holiday/ Rest & Relax   432.866667  ...   
3                                             Others   368.285714  ...   
4   Others - Personal (e.g. weddings, funerals, etc)   315.254902  ...   
5                              Holiday/ Rest & Relax   361.555556  ...   
6                              Holiday/ Rest & Relax   341.937500  ...   
7                              Holiday/ Rest & Relax   341.937500  ...   
8                              Holiday/ Rest & Relax   621.195652  ...   
9                              Holiday/ Rest & Relax   341.937500  ...   
10                             Holiday/ Rest & Relax   341.937500  ...   
11                             Holiday/ Rest & Relax   310.762963  ...   
12                                            Others   368.285714  ...   
13                             Holiday/ Rest & Relax   315.254902  ...   
14                        Visiting friends/relatives   891.375000  ...   
15  Others - Personal (e.g. weddings, funerals, etc)   310.762963  ...   
16                             Holiday/ Rest & Relax   368.285714  ...   
17                             Holiday/ Rest & Relax   341.937500  ...   
18  Others - Personal (e.g. weddings, funerals, etc)   651.269231  ...   
19                             Holiday/ Rest & Relax   419.090000  ...   

   tototh_$ totshopping_$     totexp_$  \
0       0.0    854.853136  1096.186995   
1       0.0    171.519802   379.309926   
2       0.0    104.853136   420.

In [6]:
data.describe()

case         Year  Weights_QTR    shop_$fash     shop_$jew  \
count   8887.000000  8887.000000  8887.000000   8807.000000   8807.000000   
mean   11521.140880  2014.503545   592.199788     84.202886      4.073048   
std     6615.259259     0.500016   352.449669    347.318349    124.264357   
min       15.000000  2014.000000     0.000000      0.000000      0.000000   
25%     5623.500000  2014.000000   419.090000      0.000000      0.000000   
50%    11381.000000  2015.000000   534.883333      0.000000      0.000000   
75%    17418.500000  2015.000000   666.422535     70.000000      0.000000   
max    23243.000000  2015.000000  8958.000000  15000.000000  10000.000000   

         shop_$wat   shop_$well   shop_$food   shop_$gift   shop_$ctec  ...  \
count  8807.000000  8807.000000  8807.000000  8807.000000  8807.000000  ...   
mean      5.078301    19.603905    23.220032     7.454479    13.223605  ...   
std      80.738276    80.528533    61.717987    34.570943   100.795269  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     0.000000    30.000000     0.000000     0.000000  ...   
max    4500.000000  2000.000000  2150.000000  1375.000000  3500.000000  ...   

          shop_$any     totacc_$     totfnb_$    tottran_$     totbiz_$  \
count   8807.000000  8887.000000  8887.000000  8887.000000  8887.000000   
mean     167.022502   182.091335    88.972969    35.138836     3.388864   
std      443.041314   270.410515   140.990364    45.102560    86.199504   
min        0.000000     0.000000     0.000000     0.000000     0.000000   
25%        1.633333     0.000000    15.322785    11.361328     0.000000   
50%       55.000000    77.870370    55.146940    23.197952     0.000000   
75%      175.000000   275.810124   116.015031    42.670908     0.000000   
max    15000.000000  3129.199893  5802.015116   786.019694  6000.000000   

          totedu_$      totmedi_$     tototh_$  totshopping_$      totexp_$  
count  8887.000000    8887.000000  8887.000000   8.887000e+03  8.887000e+03  
mean      3.001575     216.271980     0.568938   3.155676e+03  3.685110e+03  
std     114.616839    2234.957037     7.632622   2.735708e+05  2.736304e+05  
min       0.000000       0.000000     0.000000   8.086393e+01  8.086393e+01  
25%       0.000000       0.000000     0.000000   1.018482e+02  2.070473e+02  
50%       0.000000       0.000000     0.000000   1.480251e+02  4.279709e+02  
75%       0.000000       0.000000     0.000000   2.680251e+02  8.552404e+02  
max    9000.000000  100000.000000   350.000000   2.578999e+07  2.579524e+07  

[8 rows x 22 columns]

In [15]:
data['intv_nam'].unique()

array(['Cindy Liu', 'Philip Chew', 'Bay Poh Choo', 'Simon', 'Shariffah',
       'Adwen', 'Noraini', 'Teck Ghee', 'Anderson Yu Tor Kim', 'Bhadrul',
       'Chris', 'Felicia', 'Nizam', 'Patrick lim', 'Jay', 'CI', 'PC',
       'S1', 'And', 'Patrick Lim', 'Anees', 'Joeypoh', 'Cl', 'Sharon Hsu',
       'Sarah', 'Angeline Cheong', 'Shanon Lim', 'Cindy Lim', 'Sharrifah',
       'BAY POH CHOO', 'Cindy liu', 'Meri', 'Janelle', 'Cindy Pang'],
      dtype=object)

In [16]:
data['Country_residence'].unique()

array(['Indonesia'], dtype=object)

In [17]:
data['Purpose_grp'].unique()

array(['Leisure', 'Others/ Refused', 'Healthcare+Accompanying Pax',
       'Business+Accompanying Pax', 'Education+Accompanying Pax'],
      dtype=object)

In [19]:
data['Purpose'].unique()

array(['Holiday/ Rest & Relax', 'Others',
       'Others - Personal (e.g. weddings, funerals, etc)',
       'Visiting friends/relatives',
       'To take or join a regional or international cruise',
       'Outpatient consultation/treatment',
       'Visiting an international student studying in Singapore',
       'Accompanying a Healthcare/medical visitor for Outpatient consultation/treat',
       'General business purpose', 'Sightseeing/ Attractions', 'Stopover',
       'Others - Work Related (e.g. visa, insurance, etc)',
       'Student events', 'To shop/attend shopping events in Singapore',
       'Company sponsored holiday',
       'Executive training, including training workshops and seminar',
       'Corporate/business meetings', 'IR (e.g. MBS, RWS)',
       'Convention/conference',
       'Skills development/skills training/vocational training',
       'Exhibition/Trade show', 'In-patient treatment',
       'Student enrichment programmes', 'In-house company training',
       'M

In [20]:
data['Air_Terminal'].unique()

array(['Terminal 1', nan, 'Terminal 2', 'Terminal 3'], dtype=object)

In [22]:
data['Land_Terminal'].unique()

array([nan, 'Tuas', 'Woodlands'], dtype=object)

In [23]:
data['Sea_Terminal'].unique()

array([nan, 'RFT', 'MBCCS', 'TMFT', 'HCC'], dtype=object)

In [25]:
data['langint'].unique()

array(['English', 'Chinese', 'Malay', 'Hybrid Chinese', 'Indonesian',
       'Hybrid Indonesian', 'Japanese', 'Hybrid French'], dtype=object)

In [28]:
data['length_stay'].unique()

array(['4 days', '2 days', '3 days', '1 day', '5 days', 'Under 1 day',
       '8-10 days', '6 days', '7 days', '15-29 days', '11-14 days',
       '30-59 days', '60 days & over'], dtype=object)

In [32]:
data['shop_$oth'].unique()

array([0.00000000e+00, 3.60000000e+01, 7.50000000e+00, 3.00000000e+01,
                  nan, 8.50000000e+01, 1.00000000e+02, 2.00000000e+02,
       1.25000000e+02, 1.30000000e+02, 5.00000000e+01, 2.20000000e+02,
       1.00000000e+01, 1.50000000e+02, 2.25000000e+01, 4.45000000e+01,
       1.00000000e+00, 1.15000000e+02, 2.70000000e+01, 2.65000000e+01,
       2.40000000e+01, 7.00000000e+01, 6.00000000e+02, 6.66666667e+01,
       1.89000000e+02, 6.00000000e+01, 8.00000000e+01, 2.00000000e+01,
       6.30000000e+01, 2.14285714e+01, 2.20000000e+01, 3.50000000e+01,
       4.50000000e+01, 7.50000000e+01, 4.00000000e+01, 2.50000000e+01,
       5.00000000e+00, 1.60000000e+02, 1.75000000e+01, 2.33333333e+01,
       1.80000000e+01, 7.10000000e+01, 3.20000000e+01, 1.50000000e+01,
       1.60000000e+01, 2.50000000e+02, 2.72727273e+00, 1.06666667e+01,
       3.00000000e+02, 1.08000000e+02, 3.19000000e+02, 1.90000000e+01,
       8.70000000e+01, 4.25000000e+01, 5.50000000e+01, 2.31000000e+02,
      

In [34]:
data['travel_companion.1'].unique()

array(['Spouse', 'Partner/ Boyfriend/ Girlfriend',
       'Parents/ Parents-in-law', 'Friends', 'Alone', 'Siblings',
       'Others', 'Children aged 8-12 yrs', 'Children aged 20-39 yrs',
       'Business associates/ Colleagues', 'Children aged 13-19 yrs',
       'Other relatives', 'Children aged 0-7 yrs',
       'Grandparents/ Grandparents-in-law',
       'Children aged 40 yrs and above'], dtype=object)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8887 entries, 0 to 8886
Data columns (total 48 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   case                8887 non-null   int64         
 1   Year                8887 non-null   int64         
 2   R.mth               8887 non-null   object        
 3   date                8887 non-null   datetime64[ns]
 4   intv_nam            8887 non-null   object        
 5   Country_residence   8887 non-null   object        
 6   City_residence      8887 non-null   object        
 7   Purpose_grp         8887 non-null   object        
 8   Purpose             8887 non-null   object        
 9   Weights_QTR         8887 non-null   float64       
 10  Air_Terminal        5697 non-null   object        
 11  Sea_Terminal        2828 non-null   object        
 12  Land_Terminal       355 non-null    object        
 13  langint             8887 non-null   object      

In [8]:
data.isnull().sum()

case                     0
Year                     0
R.mth                    0
date                     0
intv_nam                 0
Country_residence        0
City_residence           0
Purpose_grp              0
Purpose                  0
Weights_QTR              0
Air_Terminal          3190
Sea_Terminal          6059
Land_Terminal         8532
langint                  0
1st_visit                0
length_stay              0
travel_type              0
f1_gender                0
f3_occupation            0
f4_industry           2844
f5_designation        3096
f5_designation.oth    2969
shop_$fash              80
shop_$jew               80
shop_$wat               80
shop_$well              80
shop_$food              80
shop_$gift              80
shop_$ctec              80
shop_$anti              80
shop_$oth               80
shop_$any               80
totacc_$                 0
totfnb_$                 0
tottran_$                0
totbiz_$                 0
totedu_$                 0
t

In [12]:
data['case'].describe()

count     8887.000000
mean     11521.140880
std       6615.259259
min         15.000000
25%       5623.500000
50%      11381.000000
75%      17418.500000
max      23243.000000
Name: case, dtype: float64

In [10]:
data.shape

(8887, 48)